config/routes.rb
Rails.application.routes.draw do

  get 'calendar/calendar'

  root 'public#welcome'
  get 'about' => 'public#about', as: 'about'
  get 'contact' => 'public#contact', as: 'contact'
  get 'calendar' => 'calendar#calendar', as: 'calendar'

  resources :blogs
  resources :events

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def calendar
  	@event = Event.new
  	@events = Event.where(date: Date.today)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	
	respond_to :js, :json

  def index
    @events = Event.all
  end

	def show
		@event = nil
	end

	def create
		@event = Event.new(events_params)

		if @event.save!
      flash[:notice] = "Even successfully added!" 
			respond_with @event 
		else
      flash[:alert] = "Could not add event! Try again."
		end
	end	

	private

	def events_params
		params.require(:event).permit(:title, :description, :start_time, :end_time, :date)
	end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def welcome
  end

  def about
  end

  def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def controller_assets
    controller = params[:controller]
    
    if Rails.application.config.x.controller_with_assets.include? controller
      javascript_include_tag("#{controller}/#{controller}", 'data-turbolinks-track' => true)  + stylesheet_link_tag(controller, 'data-turbolinks-track' => true)
    end
  end
  
  def page_title(title)
  	content_for(:title) do 
  		title
  	end
  end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/blogs/_form.html.haml
= simple_form_for(@blog) do |f|
  = f.error_messages

  = f.input :title
  = f.input :content

  = f.submit 'Post Blog'

app/views/blogs/create.html.haml
%h1 Blogs#create
%p Find me in app/views/blogs/create.html.haml

app/views/blogs/destroy.html.haml
%h1 Blogs#destroy
%p Find me in app/views/blogs/destroy.html.haml

app/views/blogs/index.html.haml
- page_title('Blogs')
- for blog in @blogs
  %article.post-container
    .post-header
      %h4<> 
        = "#{blog.title}"
    .post-content
      %p<> 
        = "#{blog.subject}"
    .post-button
      %a{:href => "#"}
        Read More

app/views/blogs/new.html.haml
%h1 Blogs#new
%p Find me in app/views/blogs/new.html.haml

app/views/blogs/update.html.haml
%h1 Blogs#update
%p Find me in app/views/blogs/update.html.haml

app/views/calendar/calendar.html.haml
- page_title('My Calendar')
.calendar_page_wrapper
  #calendar
    .external_event_wrapper
      %h3 Calendar Events
      .event
        School
      .event
        Work
  

  .events_info
    = render partial: 'events/show'

  .add_event
    = render 'events/events_form'
      

app/views/events/_events_form.html.haml
= simple_form_for(@event, remote: true, html: { class: 'event_form'}) do |f|
  = f.input :title, placeholder: 'Title', label: false
  = f.input :description, as: :text, placeholder: 'Description', label: false
  = f.input :date, as: :date, label: false
  = f.input :start_time, label: false, as: :time
  = f.input :end_time, label: false, as: :time

  = f.submit 'Add Event'

  
/ %form#event_form
/   %a 
/     Add An Event
/   .event_container
/     %div
/       %input{:type => :text, :name => 'event_title', :placeholder => 'Title'}

/     %div
/       %textarea{ :name => 'event_description', :placeholder => 'Description', rows: 4}
/     %div
/       %input{:type => :date, title: 'date', :placeholder => 'September 10 2015'}
/     %div
/       %span
/         %input{title: 'from_time', placeholder: '00', :name => 'event_from_time'}:
/         %input{title: 'from_time',  placeholder: '00', :name => 'event_from_time'} -
        
/       %span 
/         %input{title: 'to_time',  placeholder: '06', :name => 'event_to_time'}:
/         %input{title: 'to_time',  placeholder: '00', :name => 'event_to_time'}
    
/     %div
/       %button#add_event
/         Add Event

app/views/events/_show.html.haml
%h3
  = Date.today
  - for event in @events
    %ul 
      %li
        = event.title
        %span.event_time
          = "#{event.start_time.to_s(:time)} - #{event.end_time.to_s(:time)}"

app/views/events/create.js.erb
$('.event_form').bind('ajax:success', function(){
	$('.event_form')[0].reset();
 	$('#calendar').fullCalendar( 'refetchEvents' );
}); 
 

app/views/layouts/_footer.html.haml
%footer
  %p.copyright<>
    &copy; Woodson Delhia 2015. All rights Reserved.

app/views/layouts/_navbar.html.haml
%nav
  .nav-container
    %header
      = link_to 'Woodson Delhia', root_path
      %small
        ウッディー
    %ul#menu
      %li
        = link_to 'About Me', about_path
      %li
        = link_to 'Blog', blogs_path
      %li
        = link_to 'My Calendar', calendar_path
      %li
        = link_to 'Contact', about_path
    
    .menu-button
      .menu-bar
        &#8801;

%ul#device-menu
  %li.about_icon<>
    = link_to '', about_path, class: 'li_user'
  %li.blogs_icon<>
    = link_to '', blogs_path, class: 'li_bubble'
  %li.calendar_icon<>
    = link_to '', calendar_path, class: 'li_calendar'
  %li.study_icon<> 
    = link_to '', '#', class: 'li_study'
  %li.mail_icon<>
    = link_to '', contact_path, class: 'li_mail'

          

app/views/layouts/_sidebar.html.haml
%aside.sidebar
  My Side Bar
  
  .color-pallette
    .color-box{title: 'f0ecd8', aria:{ hidden:"true"}, data:{ icon:"&#xe000;"}}
    .color-box{title: '75d1c5'}
    .color-box{title: '357e8f'}
    .color-box{title: '142940'}
    .color-box{title: '802c2a'}
    .color-box{title: 'd6757e'}

  %ul#sidebar-menu
    %li
      = link_to 'About Me', about_path
    %li
      = link_to 'Blog', blogs_path
    %li
      = link_to 'School', '#'
    %li
      = link_to 'My Calendar', calendar_path
    %li
      = link_to 'Contact', about_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    %title
      = yield(:title).empty? ? 'Woodson Delhia' : yield(:title)
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = controller_assets
    = csrf_meta_tags
  %body
    = render 'layouts/sidebar'
    = render 'layouts/navbar'
    #site-wrapper
      .section.group.page-container
        = yield
      .section.group
        = render 'layouts/footer'